name: Android UI Tests

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run UI Tests
        run: ./gradlew connectedDebugAndroidTest
        env:
          EMULATOR_VERSION: 30 # Adjust the emulator version as needed

      - name: Upload Test Results
        uses: actions/upload-artifact@v1
        with:
          name: test-results
          path: app/build/outputs/androidTest-results/connected
